export const ActionTypes = {
    SET_CATEGORIES_PRODUCTS: "SET_CATEGORIES_PRODUCTS",
    SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
    SET_CURRENCIES: "SET_CURRENCIES",
    SET_SELECTED_CURRENCY: "SET_SELECTED_CURRENCY",
    TOGGLE_CURRENCY_SELECTOR: "TOGGLE_CURRENCY_SELECTOR",
    SET_PRODUCTS: "SET_PRODUCTS",
    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    TOGGLE_MINI_CART: "TOGGLE_MINI_CART"
}